### ISSUE TITLE
I hate English

### ISSUE THREAD

**Issue by Leehyowon** [namhyein/CURLY-FORTNIGHT#15]
영어 짱시룸 피피티 영어로 해야한다는 거 잘못 들은 거 였으면 좋겠다

**Comment by Seogeurim** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ효워나 갑자기 브랜치들은왜 생긴거닠ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by Leehyowon** [comment]
브랜치 예젖ㄴ에만들었었는데 그래프에없길래 ?? 했었거든? 근데지금보니까 갑자기다반영됨 ??????????????? 이상이상 나도브랜치를만들줄알았던거라고!!!!!!! 난내가못만드는줄알고 왜안되지했자나!!!!!!!!!!!!!

**Comment by Leehyowon** [comment]
근데 발표끝났으니까 이슈ㅂㅂ 혜이나수고했어
