### ISSUE TITLE
How can I make branch?

### ISSUE THREAD

**Issue by Leehyowon** [namhyein/CURLY-FORTNIGHT#6]
파일 커밋할 때 브랜치 만들어서 진행하고 싶은데
계속 오류가 나서 결국은 마스터브랜치에 직접 커밋했어
혹시 브랜치 만들어 본 사람 있어?

**Comment by namhyein** [comment]
git checkout -b <branchname>

**Comment by namhyein** [comment]
or you can make branch at github page

**Comment by namhyein** [comment]
click branch -> find or create branch -> input name whatever you want.
then you can find branch that you made
